sudo: false
language: go
go:
- 1.9
go_import_path: github.com/f5devcentral/terraform-provider-bigip
testacc:
- make test
script:
- go vet ./...
- make test
- make bin
after_success:
- make dist
deploy:
  provider: releases
  api_key:
    secure: "inU52S14fE2e2aycuTTRPxc1b1kfsj/+G07Q+Q8+oIpHLoSMqcKr/6Z4pHJr7GnUopH7xxavFwHp9m4c6+jBvh1lyCzyj3kp5VXzIQmA3zYNe/XhZoXfbY9itg1UmzgrMUDf3AFNz0U6WBX3LgYxM8Hz7+oJECSiQyXLnwS6jx/qwtSkGpo8j+vInOCi570Pg62/5Ddo8BW9vDmEWuDsqwFcs34mc0Pg5laTSB2PDEsafxsjaQcKbxYuZhg3s4IlOtTwgVwDfVgHsWnZYnvV+f7tjPlrkM6kQkyMKtC7iY56ouAmj2h6fZukh0YgUGTBB929d9P7UUew/2Gu8MWn5DU2B1BwcxeVVJM6XO5jPAWzoT8Z3a+HEyqL0Gvj/4VZd4900NolOOIuC8pE9iOaxwDx3Mw8YcjwoUAOyTtgd5sgHkqKIPM5f2GgRbLsf4hznHKlTTm1rMQlDLvnkbkCNmS3q7OMevtneptl6XnPmxC37eODlplOOyognHlnPQ7ZheiFTNHJKBUe8G/i+WFi3TIYMZc6yGxsgBkPOOFozpvNavVfmA6+q5Af2PS3xnIC8FhmLlJ3bvxSJkA4q0oB4477P8KMgVs3bKJ9SZzs5CnkdE5GqbVIU2Xc9XMWGj0L3jRDYSGVtyPbQpE+CVzp2e3bRvTyfmmJ6d5YdVjr9Qs="
  file: target/pkg/*.tar.gz
  on:
    tags: true
env:
  global:
    secure: "inU52S14fE2e2aycuTTRPxc1b1kfsj/+G07Q+Q8+oIpHLoSMqcKr/6Z4pHJr7GnUopH7xxavFwHp9m4c6+jBvh1lyCzyj3kp5VXzIQmA3zYNe/XhZoXfbY9itg1UmzgrMUDf3AFNz0U6WBX3LgYxM8Hz7+oJECSiQyXLnwS6jx/qwtSkGpo8j+vInOCi570Pg62/5Ddo8BW9vDmEWuDsqwFcs34mc0Pg5laTSB2PDEsafxsjaQcKbxYuZhg3s4IlOtTwgVwDfVgHsWnZYnvV+f7tjPlrkM6kQkyMKtC7iY56ouAmj2h6fZukh0YgUGTBB929d9P7UUew/2Gu8MWn5DU2B1BwcxeVVJM6XO5jPAWzoT8Z3a+HEyqL0Gvj/4VZd4900NolOOIuC8pE9iOaxwDx3Mw8YcjwoUAOyTtgd5sgHkqKIPM5f2GgRbLsf4hznHKlTTm1rMQlDLvnkbkCNmS3q7OMevtneptl6XnPmxC37eODlplOOyognHlnPQ7ZheiFTNHJKBUe8G/i+WFi3TIYMZc6yGxsgBkPOOFozpvNavVfmA6+q5Af2PS3xnIC8FhmLlJ3bvxSJkA4q0oB4477P8KMgVs3bKJ9SZzs5CnkdE5GqbVIU2Xc9XMWGj0L3jRDYSGVtyPbQpE+CVzp2e3bRvTyfmmJ6d5YdVjr9Qs="
