sudo: false

language: go

go:
- 1.9

go_import_path: github.com/f5devcentral/terraform-provider-bigip

testacc:
- make test

script:
- go vet ./...
- make test
- make bin

after_success:
- make dist

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  skip_cleanup: true
  file_glob: true
  file: target/pkg/*.tar.gz
  on:
    tags: true
env:
  global:
    
